name: test action

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 12

      - run: npm ci

      - name: run tests
        working-directory: ${{ github.workspace }}
        run: ls -lh bin/test; bin/test
